// Auto-generated Vietnamese UI translation layer for Codex Switcher v0.7.18.
// Only DOM-visible text/attributes are translated; application logic is untouched.
const VI_TRANSLATIONS: Record<string, string> = {
  "切号": "chuyển tài khoản",
  "、": ", ",
  "和": "và",
  "到": "vào",
  "。": ".",
  "（": "(",
  "）": ")",
  "仅": "chỉ",
  "条": "mục",
  "点": "Nhấn",
  "日": "Ngày",
  "月": "Tháng",
  "近": "Trong",
  "侧": "phía",
  "老": "cũ",
  "邀请接口返回 HTTP": "API lời mời trả về HTTP",
  "非 JSON 响应": "phản hồi không phải JSON",
  "可能需要官方桌面版登录会话": "có thể cần phiên đăng nhập ứng dụng desktop chính thức",
  "无法确认活动资格": "không thể xác nhận điều kiện tham gia",
  "邀请使用 ChatGPT 桌面版": "Mời sử dụng ChatGPT Desktop",
  "ChatGPT 桌面版邀请与奖励": "Lời mời và phần thưởng ChatGPT Desktop",
  "正在查询活动资格": "Đang kiểm tra điều kiện tham gia",
  "当前账号暂未开放此邀请活动": "Tài khoản hiện tại chưa được mở tính năng lời mời này",
  "邀请": "lời mời",
  "共": "Tổng",
  "与": "và",
  "后端已持久化的需重登状态需要重新读取账号列表": "Nếu phần phụ trợ vẫn tồn tại và cần đăng nhập lại, danh sách tài khoản cần được đọc lại.",
  "周期保鲜会在额度窗口到点后自动发一次最小": "Việc bảo quản định kỳ sẽ tự động cấp số tiền tối thiểu sau khi đạt đến thời hạn hạn ngạch.",
  "删除后有关该账号的本地授权信息将被清除": "Sau khi xóa, thông tin ủy quyền cục bộ về tài khoản sẽ bị xóa.",
  "奖励需对方接受邀请并完成官方要求后到账": "Phần thưởng phải được nhận sau khi bên kia chấp nhận lời mời và hoàn thành các yêu cầu chính thức.",
  "关闭后这类号出错会把错误透传给客户端": "Sau khi đóng, các lỗi trong loại tài khoản này sẽ được truyền tải một cách minh bạch tới khách hàng.",
  "系统可能会弹窗要求输入密码以获得权限": "Hệ thống có thể bật lên yêu cầu nhập mật khẩu để truy cập.",
  "读到这么多字节还没见到内容事件就放行": "Sau khi đọc nhiều byte như vậy, nó sẽ được giải phóng mà không thấy sự kiện nội dung.",
  "后端原始报错翻译成人能看懂的一句话": "Phần báo lỗi gốc ở phía sau được dịch thành câu mà người lớn có thể hiểu được.",
  "浏览器跳不回本机时手动提交回调链接": "Gửi liên kết gọi lại theo cách thủ công khi trình duyệt không thể quay lại máy cục bộ",
  "账号剩余配额低于此百分比时强制切号": "Khi hạn ngạch còn lại của tài khoản thấp hơn tỷ lệ phần trăm này, số sẽ buộc phải chuyển đổi.",
  "量大但要确认你愿意花对应套餐的额度": "Số lượng lớn nhưng bạn phải đảm bảo sẵn sàng chi số tiền của gói tương ứng.",
  "剩余周配额低于此百分比时提前切号": "Nếu hạn ngạch hàng tuần còn lại thấp hơn tỷ lệ phần trăm này, số lượng sẽ bị cắt trước",
  "开启后这类号跟订阅号同等参与轮询": "Sau khi được bật, loại tài khoản này sẽ tham gia bình chọn giống như tài khoản đăng ký.",
  "开弹窗并拉取该号所有可用重置次数": "Mở một cửa sổ bật lên và kéo tất cả thời gian đặt lại có sẵn cho tài khoản này",
  "授权将在你系统的默认浏览器中完成": "Việc ủy ​​quyền sẽ được thực hiện trong trình duyệt mặc định của hệ thống của bạn",
  "目前没有提供可靠的订阅到期日接口": "Hiện tại không có giao diện ngày hết hạn đăng ký đáng tin cậy được cung cấp",
  "该账号当前没有可用的主动重置次数": "Hiện tại không có cài đặt lại nào đang hoạt động cho tài khoản này",
  "邮件送达及奖励到账以官方记录为准": "Việc gửi email và nhận phần thưởng phải tuân theo hồ sơ chính thức.",
  "保证上下与有数据的格子严格对齐": "Đảm bảo rằng phần trên và phần dưới được căn chỉnh chặt chẽ với lưới dữ liệu",
  "切号时在屏幕右上角弹出系统通知": "Khi chuyển số, hệ thống sẽ hiện thông báo ở góc trên bên phải màn hình.",
  "剩余配额低于此百分比时提前切号": "Nếu hạn ngạch còn lại thấp hơn tỷ lệ này thì số lượng sẽ bị cắt trước.",
  "后端会处理打开浏览器和启动监听": "Phần phụ trợ sẽ xử lý việc mở trình duyệt và khởi động trình nghe",
  "当前的账号状态与官方文件不一致": "Trạng thái tài khoản vãng lai không nhất quán với các tài liệu chính thức",
  "手工账号到期日按本地自然日计算": "Ngày hết hạn tài khoản thủ công được tính dựa trên ngày tự nhiên địa phương",
  "文件被外部进程改动这种边角场景": "Một kịch bản góc trong đó tệp được sửa đổi bởi một quy trình bên ngoài",
  "自动循环刷新所有账号的配额数据": "Tự động làm mới dữ liệu hạn ngạch của tất cả các tài khoản theo chu kỳ tròn",
  "请检查邮箱格式和本次可邀请人数": "Vui lòng kiểm tra định dạng email và số người bạn có thể mời lần này",
  "这一刻消耗一次主动重置回收最大": "Tại thời điểm này, một lần thiết lập lại hoạt động được sử dụng và tốc độ tái chế tối đa là",
  "我已确认上述收件人及奖励条件": "Tôi đã xác nhận những người nhận và điều kiện nhận thưởng ở trên",
  "时窗口已经重置但缓存还是旧的": "Cửa sổ đã được đặt lại nhưng bộ đệm vẫn cũ",
  "没检测到当前活跃会话不是错误": "Không phát hiện phiên hiện đang hoạt động không phải là lỗi",
  "点徽章先弹窗列出所有重置次数": "Nhấp vào huy hiệu và một cửa sổ bật lên sẽ liệt kê tất cả thời gian đặt lại.",
  "用于切换代理模式后重启或排错": "Được sử dụng để khởi động lại hoặc khắc phục sự cố sau khi chuyển chế độ proxy",
  "监听后台调度器的账号更新事件": "Nghe sự kiện cập nhật tài khoản của bộ lập lịch nền",
  "秒到期时间格式化成本地短时间": "Thời gian hết hạn giây được định dạng là thời gian ngắn cục bộ",
  "请在下方选择完整链接手动复制": "Vui lòng chọn link đầy đủ bên dưới để sao chép thủ công",
  "越大越能逮住慢上游的限额事件": "Giá trị càng lớn thì khả năng nắm bắt các sự kiện giới hạn ngược dòng chậm càng tốt.",
  "非活跃账号按独占策略保活刷新": "Tài khoản không hoạt động được duy trì và làm mới theo chính sách độc quyền",
  "不必把它放进依赖里反复重建": "Không cần phải đặt nó vào phần phụ thuộc và xây dựng lại nhiều lần",
  "且无法找回这些未同步的更新": "và không thể truy xuất các bản cập nhật không đồng bộ này",
  "出口不稳但本机出口稳的场景": "Kịch bản xuất khẩu không ổn định nhưng xuất khẩu trong nước ổn định",
  "分离常规切号与系统后台任务": "Tách biệt các tác vụ chuyển đổi số thông thường và tác vụ nền hệ thống",
  "对话中插入一条切号提示消息": "Chèn tin nhắn nhắc đổi số vào cuộc trò chuyện",
  "导入后可在账号详情中手动选": "Sau khi nhập, bạn có thể chọn thủ công trong chi tiết tài khoản.",
  "成功后清空输入避免重复提交": "Xóa đầu vào sau khi thành công để tránh gửi lại",
  "批量导入结果保留到下次打开": "Kết quả nhập hàng loạt được giữ lại cho đến lần tiếp theo bạn mở chúng",
  "整批的尾延迟会跟着慢账号走": "Sự chậm trễ của toàn bộ đợt sẽ theo tài khoản chậm",
  "现在用一次主动重置回收最大": "Bây giờ hãy sử dụng thiết lập lại hoạt động để tái chế tối đa",
  "系统默认自动管理全部订阅号": "Hệ thống tự động quản lý tất cả tài khoản thuê bao theo mặc định",
  "被撤销或会话在其他设备结束": "bị thu hồi hoặc phiên kết thúc trên thiết bị khác",
  "请在打开的浏览器窗口中完成": "Vui lòng hoàn thành nó trong cửa sổ trình duyệt đang mở",
  "请粘贴到目标浏览器完成授权": "Vui lòng dán nó vào trình duyệt mục tiêu để hoàn tất ủy quyền",
  "首次遇到无法确认是否激活的": "Lần đầu tiên tôi gặp phải thứ gì đó mà tôi không thể xác nhận liệu nó đã được kích hoạt hay chưa.",
  "代理正在注入当前激活号的": "Đại lý đang tiêm số kích hoạt hiện tại",
  "任意填一个非空字符串即可": "Chỉ cần điền vào bất kỳ chuỗi không trống",
  "但我们这里可以再打印一下": "Nhưng chúng ta có thể in lại ở đây",
  "发送邀请不代表奖励已到账": "Gửi lời mời không có nghĩa là đã nhận được phần thưởng.",
  "可以把同一个服务添加多次": "Bạn có thể thêm cùng một dịch vụ nhiều lần",
  "可直接连接这台机器的代理": "Đại lý có thể kết nối trực tiếp với máy này",
  "同一窗口内任意两次快照的": "Bất kỳ hai ảnh chụp nhanh nào trong cùng một cửa sổ",
  "同邮箱已存在的账号会跳过": "Các tài khoản đã tồn tại có cùng địa chỉ email sẽ bị bỏ qua",
  "在路由列表里显示这个名字": "Hiển thị tên này trong danh sách định tuyến",
  "官方插件中的当前登录状态": "Trạng thái đăng nhập hiện tại trong plugin chính thức",
  "是去掉异常值后最稳的估计": "là ước tính ổn định nhất sau khi loại bỏ các ngoại lệ",
  "样本会随每次切号自动累积": "Mẫu sẽ được tự động cộng dồn sau mỗi lần cắt số",
  "点击查看所有主动重置次数": "Nhấp để xem tất cả thời gian thiết lập lại đang hoạt động",
  "等首个内容事件最长等多久": "Bạn nên đợi sự kiện nội dung đầu tiên trong bao lâu?",
  "简单返回第一个非当前账号": "Chỉ cần quay lại tài khoản phi hiện tại đầu tiên",
  "一旦边缘节流单个账号要": "Sau khi yêu cầu điều chỉnh biên cho một tài khoản,",
  "主动开始新的滚动倒计时": "Tích cực bắt đầu đếm ngược lần lăn mới",
  "从浏览器地址栏复制完整": "Sao chép hoàn chỉnh từ thanh địa chỉ trình duyệt",
  "但额度查询不会自动进行": "Tuy nhiên, việc điều tra hạn ngạch sẽ không được thực hiện tự động.",
  "再关闭并重新打开此窗口": "Đóng và mở lại cửa sổ này",
  "再消耗一次重置限额窗口": "Dành thêm một thời gian để thiết lập lại cửa sổ giới hạn",
  "把授权链接复制到剪贴板": "Sao chép liên kết ủy quyền vào khay nhớ tạm của bạn",
  "是否允许自动寻找并切到": "Có cho phép tự động tìm kiếm và chuyển sang",
  "检查是否有未同步的官方": "Kiểm tra xem có chính thức chưa đồng bộ không",
  "正在启动官方浏览器授权": "Bắt đầu ủy quyền trình duyệt chính thức",
  "每个账号之间的刷新间隔": "Khoảng thời gian làm mới giữa mỗi tài khoản",
  "每位符合条件的邀请奖励": "Phần thưởng cho mỗi lời mời đủ điều kiện",
  "每轮循环刷新多少个账号": "Có bao nhiêu tài khoản được làm mới trong mỗi chu kỳ?",
  "消耗完成后无条件关弹窗": "Đóng cửa sổ bật lên vô điều kiện sau khi tiêu thụ xong",
  "窗口时只发一次极小请求": "Chỉ gửi một yêu cầu rất nhỏ một lần trong thời gian này",
  "试试调整搜索词或切换到": "Hãy thử điều chỉnh cụm từ tìm kiếm của bạn hoặc chuyển sang",
  "调度器才会尝试保活刷新": "Bộ lập lịch sẽ cố gắng duy trì và làm mới",
  "这类返回的百分比剩余值": "Lớp này trả về phần trăm giá trị còn lại",
  "这里不卡死方便本地场景": "Nó không bị kẹt ở đây và thuận tiện cho các cảnh địa phương.",
  "这里可以单独关闭该账号": "Bạn có thể đóng tài khoản này riêng lẻ tại đây",
  "选好会话和账号即可添加": "Chọn phiên và tài khoản để thêm",
  "高级设置可添加其他模型": "Cài đặt nâng cao để thêm các mô hình bổ sung",
  "不会当作额度重置时间": "Nó sẽ không được coi là thời gian thiết lập lại hạn ngạch",
  "不查配额请把策略改成": "Nếu bạn không muốn kiểm tra hạn ngạch, vui lòng thay đổi chính sách thành",
  "主界面颜色的色调风格": "Kiểu tông màu của màu sắc giao diện chính",
  "代理关闭时回退到冷切": "Dự phòng để cắt nguội khi tắt proxy",
  "代理已自动切换到账号": "Đại lý đã tự động chuyển sang tài khoản",
  "代理开启时自动走热切": "Tự động chuyển sang điểm phát sóng khi tác nhân được bật",
  "会话强制使用某个账号": "Phiên buộc phải sử dụng tài khoản",
  "后用该账号发一次最小": "Sau đó sử dụng tài khoản này để gửi tối thiểu",
  "周配额预防性切号阈值": "Ngưỡng cắt giảm số lượng hạn ngạch hàng tuần",
  "回调会自动回到本应用": "Cuộc gọi lại sẽ tự động quay lại ứng dụng này",
  "因此这里由你手工维护": "Vì vậy, điều này được bạn duy trì bằng tay",
  "在该窗口内的精确求和": "Tổng hợp chính xác trong cửa sổ này",
  "复用同一个进度条渲染": "Sử dụng lại kết xuất thanh tiến trình tương tự",
  "实际调用仍使用上面的": "Cuộc gọi thực tế vẫn sử dụng cách trên",
  "强制终止所有运行中的": "Buộc chấm dứt mọi hoạt động",
  "当前可用次数无法确认": "Không thể xác nhận thời gian sẵn có hiện tại",
  "当前账号只做权威回流": "Tài khoản hiện tại chỉ thực hiện chỉnh sửa có thẩm quyền",
  "手机远程连接绑定此号": "Kết nối từ xa của điện thoại di động bị ràng buộc với số này",
  "授权链接复制到剪贴板": "Đã sao chép liên kết ủy quyền vào bảng nhớ tạm",
  "支持无中断自动切号和": "Hỗ trợ chuyển số tự động mà không bị gián đoạn và",
  "无配额限制按用量计费": "Không giới hạn hạn ngạch Thanh toán khi bạn di chuyển",
  "既不雷霆万钧也不串行": "Cả Thunderbolt lẫn Serial",
  "未命中映射时统一替换": "Thay thế thống nhất khi ánh xạ bị thiếu",
  "未获取的窗口显示未知": "Cửa sổ không được mua lại hiển thị không xác định",
  "正在拉取重置次数明细": "Kéo chi tiết số đặt lại",
  "消耗哪条由服务端决定": "Cái nào được tiêu thụ được xác định bởi máy chủ.",
  "由你粘贴到目标浏览器": "Được bạn dán vào trình duyệt mục tiêu",
  "监听后台刷新失败事件": "Lắng nghe các sự kiện lỗi làm mới nền",
  "监听后端发来的授权码": "Nghe mã ủy quyền được gửi từ chương trình phụ trợ",
  "窗口内触发过限额切号": "Chuyển đổi số được kích hoạt trong cửa sổ nếu vượt quá giới hạn",
  "自动切到健康的订阅号": "Tự động chuyển sang tài khoản đăng ký lành mạnh",
  "让用户知道开关有意义": "Cho người dùng biết switch có ý nghĩa",
  "设为其模型的当前账号": "Tài khoản hiện tại được đặt làm mô hình của nó",
  "设为这些模型的当前号": "Đặt số lượng hiện tại của các mô hình này",
  "请把余额查询策略改成": "Vui lòng thay đổi chiến lược truy vấn số dư thành",
  "隔离属性修复仅适用于": "Sửa lỗi thuộc tính riêng biệt chỉ áp dụng cho",
  "首次加载时扫描补录新": "Quét và thêm tập tin mới khi tải lần đầu tiên",
  "上游未提供重置时间": "Không có thời gian thiết lập lại được cung cấp bởi thượng nguồn",
  "上游未返回重置次数": "Không có số lần đặt lại được trả về từ thượng nguồn",
  "中手动改了登录状态": "Thay đổi trạng thái đăng nhập theo cách thủ công",
  "中选择此中转的模型": "Chọn mô hình cho việc chuyển giao này trong",
  "也不会触发自动切号": "Nó sẽ không kích hoạt chuyển đổi số tự động.",
  "兼容服务的预设列表": "Danh sách cài sẵn các dịch vụ tương thích",
  "出问题时切回订阅号": "Chuyển về tài khoản đăng ký của bạn khi có sự cố",
  "分钟内被写过的最新": "Được viết mới nhất trong vòng vài phút",
  "切换账号后自动重载": "Tự động tải lại sau khi chuyển đổi tài khoản",
  "卡片左侧图标的文字": "Nội dung của biểu tượng ở phía bên trái của thẻ",
  "卡片选择器中的分组": "Nhóm trong bộ chọn thẻ",
  "合并到同邮箱旧账号": "Hợp nhất vào tài khoản cũ có cùng địa chỉ email",
  "后按账号发一次最小": "Sau đó nhấn số tài khoản và gửi một lần với mức tối thiểu",
  "后账号会变成不可用": "Tài khoản sẽ không còn khả dụng sau này",
  "周限额窗口立刻清零": "Cửa sổ giới hạn hàng tuần bị xóa ngay lập tức",
  "复制命令到终端运行": "Sao chép lệnh vào terminal và chạy nó",
  "实际可用模型清单由": "Danh sách thực tế của các mô hình có sẵn được cung cấp bởi",
  "将恢复全局自动切号": "Chuyển đổi số tự động toàn cầu sẽ được khôi phục",
  "开启后本机自己决定": "Sau khi bật lên thì máy tự quyết định",
  "当前账号并热切过去": "Tài khoản hiện tại và mong muốn vượt qua",
  "执行真正的切换逻辑": "Thực hiện logic chuyển đổi thực",
  "按最后更新时间排序": "Sắp xếp theo thời gian cập nhật lần cuối",
  "插件中存在未同步的": "Có plugin chưa đồng bộ",
  "支持官网或自有中转": "Hỗ trợ trang web chính thức hoặc chuyển khoản riêng",
  "是用户在控制台创建": "Được tạo bởi người dùng trong bảng điều khiển",
  "未返回已创建的邀请": "Lời mời đã tạo không được trả lại",
  "本字段是这次新增的": "Trường này mới được thêm vào lần này",
  "模型按会员权限选择": "Mô hình được lựa chọn theo quyền thành viên",
  "次会把当前已耗尽的": "Lần này hiện tại đã kiệt sức",
  "正在验证账号和项目": "Xác minh tài khoản và dự án",
  "每次切号前后强制抓": "Buộc bắt giữ trước và sau mỗi lần thay đổi số",
  "没有匹配的最近会话": "Không có phiên nào phù hợp gần đây",
  "活动未提供奖励数额": "Hoạt động không cung cấp số tiền thưởng",
  "点击设置账号到期日": "Nhấp để đặt ngày hết hạn tài khoản",
  "点击账号名打开主页": "Click vào tên tài khoản để mở trang chủ",
  "点开账号看历史周期": "Bấm vào mở tài khoản để xem chu kỳ lịch sử",
  "现在请尝试重新打开": "Vui lòng thử mở lại ngay bây giờ",
  "用于刷新父组件列表": "Được sử dụng để làm mới danh sách thành phần cha mẹ",
  "用户可在表单里覆盖": "Người dùng có thể ghi đè điều này trong biểu mẫu",
  "用户可能想再回来看": "Người dùng có thể muốn quay lại lần nữa",
  "用户手工维护的账号": "Tài khoản được người dùng duy trì theo cách thủ công",
  "用订阅号时自动切号": "Tự động chuyển đổi tài khoản khi sử dụng tài khoản thuê bao",
  "留空保存可清除日期": "Để trống để lưu để xóa ngày",
  "留空则拒绝所有请求": "Để trống để từ chối tất cả các yêu cầu",
  "确定要永久删除账号": "Bạn có chắc chắn muốn xóa vĩnh viễn tài khoản của mình không?",
  "等本地推理不需要真": "Chờ suy luận cục bộ không nhất thiết phải đúng",
  "类型账号的余额缓存": "Cân bằng bộ đệm của loại tài khoản",
  "网络或服务暂时异常": "Mạng hoặc dịch vụ tạm thời không bình thường.",
  "自动同号关了也可用": "Nó cũng có thể được sử dụng nếu tính năng khớp số tự động bị tắt.",
  "若额度还没用到上限": "Nếu hạn ngạch chưa được sử dụng đến giới hạn trên",
  "让用户看到成功提示": "Cho phép người dùng nhìn thấy lời nhắc thành công",
  "账号能正常调用模型": "Tài khoản có thể gọi model bình thường",
  "过滤胶囊只看订阅类": "Bộ lọc viên nang chỉ xem danh mục đăng ký",
  "通知父组件刷新列表": "Thông báo cho thành phần cha mẹ để làm mới danh sách",
  "配额预防性切号阈值": "Ngưỡng chuyển đổi số phòng ngừa hạn ngạch",
  "限额事件的缓冲大小": "Kích thước bộ đệm cho các sự kiện hạn ngạch",
  "除非中转站确实暴露": "Trừ khi trạm trung chuyển thực sự bị lộ",
  "需要重新粘贴一次新": "Cần dán lại cái mới",
  "预设仅提供默认地址": "Theo mặc định chỉ có địa chỉ mặc định được cung cấp",
  "不代表次数已清空": "Điều đó không có nghĩa là thời gian đã được xóa bỏ",
  "不会参与模型请求": "Sẽ không tham gia vào các yêu cầu về mô hình",
  "不可达会静默跳过": "Nếu không thể truy cập được, nó sẽ bị bỏ qua trong im lặng.",
  "不打开默认浏览器": "Không mở trình duyệt mặc định",
  "不是当前可用余额": "Không phải số dư hiện có",
  "主不通时自动切换": "Tự động chuyển đổi khi thiết bị chính không khả dụng",
  "之间切换额度的话": "Nếu bạn chuyển đổi số tiền giữa",
  "也走本机直连上游": "Bạn cũng có thể sử dụng máy cục bộ để kết nối trực tiếp với thượng nguồn.",
  "仍然按错误类型标": "Vẫn được đánh dấu theo loại lỗi",
  "保守切换也失败了": "Chuyển đổi bảo thủ cũng thất bại",
  "全球按量付费聚合": "Tổng hợp thanh toán theo mức sử dụng toàn cầu",
  "其他厂商可能撞到": "Các nhà sản xuất khác có thể đạt được",
  "其他方法保持不变": "Các phương pháp khác không thay đổi",
  "冲突确认弹窗状态": "Trạng thái bật lên xác nhận xung đột",
  "到期后需重新导入": "Cần phải nhập lại sau khi hết hạn",
  "刷新当前列表额度": "Làm mới hạn ngạch danh sách hiện tại",
  "加载代理状态失败": "Không thể tải trạng thái đại lý",
  "加载统计数据失败": "Không tải được số liệu thống kê",
  "可一次选多个文件": "Có thể chọn nhiều tập tin cùng một lúc",
  "可能影响对话状态": "Có thể ảnh hưởng đến trạng thái cuộc trò chuyện",
  "同组模型共享额度": "Hạn ngạch được chia sẻ cho các người mẫu trong cùng một nhóm",
  "后台保活临时失败": "Việc lưu giữ nền tạm thời không thành công",
  "周期保鲜最近错误": "Lỗi mới nhất của chu kỳ",
  "多账号切换更稳定": "Chuyển đổi giữa nhiều tài khoản ổn định hơn",
  "如果暂时不查配额": "Nếu bạn không tạm thời kiểm tra hạn ngạch",
  "字段需用户填实际": "Các trường cần được người dùng điền vào",
  "实际时长自动识别": "Tự động nhận biết thời lượng thực tế",
  "客户端访问需携带": "Quyền truy cập của khách hàng cần mang lại",
  "已经承担确认职责": "Đã đảm nhận trách nhiệm xác nhận",
  "已解除手机锚绑定": "Liên kết neo điện thoại di động đã được phát hành",
  "当前账号已切换为": "Tài khoản hiện tại đã được chuyển sang",
  "心跳时自动把本机": "Tự động bật máy khi có nhịp tim",
  "手动粘贴回调链接": "Dán liên kết gọi lại theo cách thủ công",
  "手机远程连接绑定": "Ràng buộc kết nối từ xa điện thoại di động",
  "指向下面这个地址": "Trỏ tới địa chỉ bên dưới",
  "按量付费独立端点": "Điểm cuối độc lập trả tiền khi bạn sử dụng",
  "支持令牌自动续期": "Hỗ trợ tự động gia hạn mã thông báo",
  "收到后台刷新通知": "Nhận thông báo làm mới nền",
  "收到设置更新通知": "Nhận thông báo cập nhật cài đặt",
  "无论中间切号几次": "Dù có bao nhiêu lần con số bị cắt ở giữa",
  "显示用的一行说明": "Mô tả một dòng để hiển thị",
  "未在内置白名单中": "Không có trong danh sách trắng tích hợp",
  "桌面版邀请与奖励": "Lời mời và phần thưởng phiên bản máy tính để bàn",
  "检查同步状态失败": "Kiểm tra trạng thái đồng bộ hóa không thành công",
  "次的开销可以接受": "Chi phí có thể chấp nhận được",
  "正在生成授权链接": "Tạo liên kết ủy quyền",
  "添加成功后的回调": "Gọi lại sau khi thêm thành công",
  "点击查询银行明细": "Bấm để kiểm tra chi tiết ngân hàng",
  "用户必须改成自己": "Người dùng phải tự thay đổi",
  "用该账号开一个真": "Sử dụng tài khoản này để mở một tài khoản thực",
  "登录状态冲突警告": "Cảnh báo xung đột trạng thái đăng nhập",
  "的旧条目默认隐藏": "Các mục cũ được ẩn theo mặc định",
  "监听设置更新事件": "Nghe các sự kiện cập nhật cài đặt",
  "目标账号已被删除": "Tài khoản mục tiêu đã bị xóa",
  "端发的所有未命中": "tất cả đều bỏ lỡ từ cuối",
  "绕过全局自动切号": "Bỏ qua chuyển đổi số tự động toàn cầu",
  "缺失时回退到通用": "Dự phòng cho phổ quát khi bị thiếu",
  "自动刷新账号额度": "Tự động làm mới hạn ngạch tài khoản",
  "获取最佳账号推荐": "Nhận đề xuất tài khoản tốt nhất",
  "请删除后重新登录": "Vui lòng xóa và đăng nhập lại",
  "请在浏览器中完成": "Vui lòng hoàn thành nó trong trình duyệt của bạn",
  "请检查长度是否为": "Vui lòng kiểm tra xem chiều dài có",
  "账号仍可正常使用": "Tài khoản vẫn có thể sử dụng bình thường",
  "账号即使导入也无": "Ngay cả khi tài khoản được nhập, sẽ không có",
  "距到期还剩多少天": "Còn bao nhiêu ngày nữa là hết hạn",
  "过期需要重新导入": "Đã hết hạn và cần được nhập lại",
  "这是活动奖励数额": "Đây là số tiền thưởng sự kiện",
  "这里关闭弹窗即可": "Chỉ cần đóng cửa sổ bật lên ở đây",
  "这里只给一个占位": "Chỉ có một phần giữ chỗ ở đây",
  "进行中也允许关闭": "Đóng cũng được cho phép trong khi đang tiến hành",
  "选预设后会自动填": "Nó sẽ được điền tự động sau khi chọn mặc định",
  "通常最早到期优先": "Thường ưu tiên hết hạn sớm nhất",
  "避免双路刷新撞飞": "Tránh xung đột làm mới kênh đôi",
  "配额查询需要粘贴": "Truy vấn hạn ngạch cần được dán",
  "重新加载账号列表": "Tải lại danh sách tài khoản",
  "风格但中间是数字": "phong cách nhưng có số ở giữa",
  "默认优先付费账号": "Tài khoản trả phí ưu tiên mặc định",
  "上展示哪个标签": "nhãn nào sẽ hiển thị trên",
  "上次数据已过期": "Dữ liệu cuối cùng đã hết hạn",
  "上游未提供状态": "Trạng thái không được cung cấp bởi thượng nguồn",
  "不一致仅出现在": "Sự mâu thuẫn chỉ xảy ra ở",
  "不会路由到中转": "Sẽ không được chuyển sang phương tiện công cộng",
  "不依赖账号打满": "Không phụ thuộc vào tài khoản được lấp đầy",
  "不显示警告而是": "Thay vì hiển thị cảnh báo",
  "不绑定套餐名称": "Không bị ràng buộc với tên gói",
  "中提取认证信息": "Trích xuất thông tin xác thực từ",
  "也可用逗号分隔": "Cũng có thể cách nhau bằng dấu phẩy",
  "也由本机自己写": "Cũng do chính máy này viết",
  "从最近会话挑选": "Chọn từ các cuộc trò chuyện gần đây",
  "代理出口已切到": "Việc xuất đại lý đã được chuyển sang",
  "代理已自动切号": "Đại lý đã tự động chuyển số",
  "会自动递归识别": "Sẽ tự động nhận dạng đệ quy",
  "使用杀进程重启": "Sử dụng quá trình kill để khởi động lại",
  "使用自有中转时": "Khi sử dụng phương tiện công cộng của riêng bạn",
  "允许局域网访问": "Cho phép truy cập mạng LAN",
  "切号现在永远写": "Số cắt bây giờ được ghi mãi mãi",
  "切换下一个账号": "Chuyển sang tài khoản tiếp theo",
  "到期当天仍显示": "Vẫn hiển thị vào ngày hết hạn",
  "加载账号和设置": "Tải tài khoản và cài đặt",
  "区别仅到期时间": "Sự khác biệt chỉ là thời gian hết hạn",
  "可选的备注信息": "Nhận xét tùy chọn",
  "可配置厂商模型": "Mô hình nhà cung cấp có thể cấu hình",
  "同一局域网内的": "trong cùng một mạng LAN",
  "后台保活与同步": "Giữ nền và đồng bộ hóa",
  "后台保活已停用": "Tính năng lưu giữ nền bị vô hiệu hóa",
  "含各自到期时间": "Bao gồm thời gian hết hạn tương ứng",
  "多用几小时即可": "Chỉ còn vài giờ nữa thôi",
  "多账号智能切换": "Chuyển đổi thông minh giữa nhiều tài khoản",
  "天没有邀请记录": "Không có bản ghi lời mời trong nhiều ngày",
  "它不会修改登录": "nó không sửa đổi thông tin đăng nhập",
  "实际支持的模型": "Các mô hình được hỗ trợ thực tế",
  "客户端无法指定": "Khách hàng không thể chỉ định",
  "密钥后点此应用": "Sau key nhấn Apply",
  "对话内注入通知": "Đưa thông báo vào cuộc trò chuyện",
  "导入中转站账号": "Nhập tài khoản trạm trung chuyển",
  "展示给用户编辑": "Hiển thị cho người chỉnh sửa người dùng",
  "已提交回调链接": "Đã gửi liên kết gọi lại",
  "已过期或被撤销": "Hết hạn hoặc bị thu hồi",
  "帮用户秒懂当前": "Giúp người dùng hiểu được tình hình hiện tại trong vài giây",
  "延迟关闭模态框": "Trì hoãn đóng hộp phương thức",
  "强约束最多一个": "Có nhiều nhất một ràng buộc mạnh",
  "慢账号自然排队": "Tài khoản chậm xếp hàng tự nhiên",
  "手机锚生效场景": "Kịch bản hiệu quả của neo điện thoại di động",
  "把会话钉到账号": "Ghim cuộc trò chuyện vào tài khoản",
  "指定浏览器登录": "Chỉ định đăng nhập trình duyệt",
  "按到期时间排序": "Sắp xếp theo thời gian hết hạn",
  "按服务支持选择": "Chọn theo dịch vụ hỗ trợ",
  "授权链接已复制": "Đã sao chép liên kết ủy quyền",
  "推送全部账号到": "Đẩy tất cả tài khoản vào",
  "搜索与过滤逻辑": "Logic tìm kiếm và lọc",
  "文档示例只给了": "Các ví dụ tài liệu chỉ cung cấp",
  "新终端窗口生效": "Cửa sổ terminal mới có hiệu lực",
  "无冲突直接切换": "Chuyển đổi trực tiếp mà không xung đột",
  "无论如何都冷切": "Dù sao cũng cắt nguội",
  "无需再手动更新": "Không còn cập nhật thủ công nữa",
  "时估计仍有偏差": "Ước tính vẫn còn sai lệch",
  "月抛账号到期日": "Ngày hết hạn tài khoản hàng tháng",
  "未判定账号失效": "Tài khoản chưa được xác định là không hợp lệ.",
  "未设置当前账号": "Tài khoản hiện tại chưa được thiết lập",
  "本地代理服务器": "máy chủ proxy cục bộ",
  "本机已强制关闭": "Máy bị buộc phải tắt",
  "本机直接打上游": "Máy này gọi trực tiếp lên thượng nguồn",
  "本次提交已结束": "Quá trình gửi này đã kết thúc",
  "此操作不可恢复": "Hoạt động này là không thể đảo ngược",
  "此操作不可撤销": "Hành động này không thể thay đổi được",
  "此操作将从所有": "Hoạt động này sẽ bắt đầu từ tất cả",
  "每轮刷新账号数": "Làm mới số lượng tài khoản trong mỗi vòng",
  "没有匹配的账号": "Không có tài khoản phù hợp",
  "浏览器没跳回来": "Trình duyệt không quay lại",
  "生效时彻底隐藏": "Ẩn hoàn toàn khi có hiệu lực",
  "用该账号在隔离": "Sử dụng tài khoản này để cô lập",
  "登录状态不一致": "Trạng thái đăng nhập không nhất quán",
  "的安全隔离属性": "thuộc tính cách ly bảo mật",
  "直连下开一个真": "Trực tiếp mở một cái thật",
  "确认覆盖并切换": "Xác nhận vùng phủ sóng và chuyển đổi",
  "窗口明细未获取": "Không thu được chi tiết cửa sổ",
  "立即导入该账号": "Nhập tài khoản này ngay bây giờ",
  "等待浏览器授权": "Đợi trình duyệt cấp phép",
  "统一替换成这个": "Thay thế nó một cách thống nhất bằng cái này",
  "翻译器目前只在": "Trình dịch hiện chỉ có sẵn trong",
  "自动选号可挑中": "Có thể chọn số tự động",
  "自动重载仅支持": "Tự động tải lại chỉ hỗ trợ",
  "请填写该中转的": "Vui lòng điền thông tin chuyển khoản",
  "请查询记录确认": "Vui lòng kiểm tra hồ sơ để xác nhận",
  "请稍后重试查询": "Vui lòng thử lại sau",
  "请输入账号名称": "Vui lòng nhập tên tài khoản",
  "账号名不能为空": "Tên tài khoản không được để trống",
  "还没有路由规则": "Chưa có quy tắc định tuyến nào",
  "这种百分比模型": "Mô hình tỷ lệ này",
  "选完进入下一步": "Sau khi chọn xong chuyển sang bước tiếp theo",
  "选择手机锚账号": "Chọn tài khoản cố định trên thiết bị di động",
  "选择文件并导入": "Chọn tệp và nhập",
  "邀请记录已创建": "Bản ghi lời mời đã được tạo",
  "配额最高的账号": "Tài khoản có hạn ngạch cao nhất",
  "重启代理后生效": "Nó sẽ có hiệu lực sau khi khởi động lại đại lý.",
  "量化误差会失真": "Lỗi lượng tử hóa sẽ làm biến dạng",
  "需要再次邀请时": "Khi bạn cần mời lại",
  "需要管理员权限": "Yêu cầu quyền quản trị viên",
  "非活跃保活阈值": "Ngưỡng duy trì không hoạt động",
  "一键切换最佳": "Chuyển đổi bằng một cú nhấp chuột là tốt nhất",
  "上完全验证过": "Đã được xác minh hoàn toàn trên",
  "上游原生支持": "Hỗ trợ gốc ngược dòng",
  "上游模型额度": "Hạn ngạch mô hình ngược dòng",
  "下一步只用粘": "Bước tiếp theo chỉ là gắn bó",
  "不代表已清空": "Không có nghĩa là nó đã được xóa",
  "不再静默失败": "Không còn những thất bại thầm lặng",
  "不能事后追溯": "Không thể hồi tố",
  "个工作区额度": "hạn ngạch khu vực làm việc",
  "个账号同时打": "Gọi nhiều tài khoản cùng lúc",
  "中转余额刷新": "Làm mới số dư chuyển khoản",
  "中转站没标准": "Trạm trung chuyển không có tiêu chuẩn",
  "中转站讲什么": "Trạm trung chuyển nói về điều gì?",
  "中转账号请用": "Vui lòng sử dụng tài khoản chuyển khoản",
  "中转都用这条": "Sử dụng cái này để chuyển",
  "主动重置次数": "Số lần đặt lại hoạt động",
  "仅重载选中的": "Chỉ tải lại đã chọn",
  "会变成双弹框": "Nó sẽ trở thành một hộp bật lên đôi",
  "会读到这个号": "Sẽ đọc số này",
  "余额查询策略": "Chiến lược điều tra số dư",
  "余额自动探测": "Tự động phát hiện cân bằng",
  "使用当前会话": "Sử dụng phiên hiện tại",
  "保持本机现状": "Giữ nguyên hiện trạng địa phương",
  "修正激活状态": "Sửa trạng thái kích hoạt",
  "免去手动复制": "Loại bỏ sao chép thủ công",
  "全部模型额度": "Tất cả hạn ngạch mô hình",
  "关闭自动重载": "Tắt tải lại tự động",
  "内部唯一标识": "mã định danh duy nhất nội bộ",
  "写入环境变量": "Viết biến môi trường",
  "切到其他号时": "Khi chuyển sang số khác",
  "切号原因分布": "Phân bố lý do cắt giảm số lượng",
  "切换检查失败": "Kiểm tra chuyển đổi không thành công",
  "删除确认弹窗": "Xóa cửa sổ bật lên xác nhận",
  "刷新模型额度": "Làm mới hạn ngạch mô hình",
  "刷新账号列表": "Làm mới danh sách tài khoản",
  "剩余奖励名额": "Hạn mức thưởng còn lại",
  "加载最近会话": "Tải các cuộc trò chuyện gần đây",
  "加载设置失败": "Không tải được cài đặt",
  "加载路由规则": "Tải quy tắc định tuyến",
  "厂商按量付费": "Các nhà sản xuất trả tiền khi họ đi",
  "厂商编程订阅": "Đăng ký lập trình nhà cung cấp",
  "反向同步覆盖": "Phạm vi đồng bộ hóa ngược",
  "同步状态失败": "Trạng thái đồng bộ hóa không thành công",
  "后台任务日志": "Nhật ký tác vụ nền",
  "后自动刷新的": "tự động làm mới sau",
  "处理官方导入": "Xử lý nhập khẩu chính ngạch",
  "复制授权链接": "Sao chép liên kết ủy quyền",
  "套餐专属端点": "Điểm cuối độc quyền của gói",
  "字段命中后端": "Phần phụ trợ của trường truy cập",
  "安全隔离属性": "thuộc tính cách ly bảo mật",
  "官方文档说明": "Tài liệu chính thức",
  "官方渠道登录": "Đăng nhập kênh chính thức",
  "定时额度刷新": "Làm mới hạn ngạch thường xuyên",
  "实际时长判断": "Phán quyết về thời hạn thực tế",
  "实际窗口配额": "hạn ngạch cửa sổ thực tế",
  "导入当前账号": "Nhập tài khoản hiện tại",
  "导入账号详情": "Nhập chi tiết tài khoản",
  "导出账号数据": "Xuất dữ liệu tài khoản",
  "将从本地官方": "từ quan chức địa phương",
  "尝试保守切换": "Hãy thử chuyển đổi thận trọng",
  "局域网客户端": "máy khách mạng LAN",
  "已生成新密钥": "Khóa mới được tạo",
  "已获取授权码": "Mã ủy quyền thu được",
  "已设为手机锚": "Đã được đặt làm quảng cáo cố định trên thiết bị di động",
  "已过期或失效": "Hết hạn hoặc không hợp lệ",
  "建议仅暴露给": "Khuyến cáo chỉ nên tiếp xúc với",
  "建议填局域网": "Nên điền LAN",
  "开启自动重载": "Bật tải lại tự động",
  "当前已被限流": "Hiện đang bị hạn chế",
  "当前活跃会话": "Phiên hiện đang hoạt động",
  "当前绑定账号": "Tài khoản hiện đang bị ràng buộc",
  "当前账号额度": "Giới hạn tài khoản vãng lai",
  "或者嵌套容器": "hoặc các thùng chứa lồng nhau",
  "批量导入文件": "Nhập tập tin theo lô",
  "拉取全部账号": "Kéo tất cả các tài khoản",
  "拉取明细失败": "Không thể kéo chi tiết",
  "按黑名单跳过": "Bỏ qua danh sách đen",
  "推送本机账号": "Đẩy tài khoản cục bộ",
  "支持单个对象": "Hỗ trợ đối tượng duy nhất",
  "支持模型映射": "Hỗ trợ ánh xạ mô hình",
  "收起全部模型": "Ẩn tất cả các mô hình",
  "改成并发上限": "Thay đổi giới hạn đồng thời",
  "新增账号详情": "Thêm chi tiết tài khoản",
  "无需显式取消": "Không cần phải hủy bỏ một cách rõ ràng",
  "日期内容异常": "Nội dung ngày bất thường",
  "日期格式异常": "Định dạng ngày bất thường",
  "旧条目里没有": "Không có trong mục cũ",
  "早期版本没记": "Tôi không nhớ phiên bản trước",
  "智能切号允许": "Cho phép chuyển đổi số thông minh",
  "智能切号策略": "Chiến lược chuyển đổi số thông minh",
  "暂无切号记录": "Chưa có hồ sơ chuyển số",
  "暂无已安装的": "Chưa có cài đặt nào",
  "暂无模型额度": "Chưa có hạn ngạch mô hình",
  "更快推理速度": "Tốc độ suy luận nhanh hơn",
  "最佳账号推荐": "Đề xuất tài khoản tốt nhất",
  "本机直连上游": "Máy này được kết nối trực tiếp với thượng nguồn",
  "本次最多邀请": "Hầu hết các lời mời lần này",
  "查看全部模型": "Xem tất cả các mô hình",
  "查看所有账号": "Xem tất cả tài khoản",
  "标记为已安装": "Đánh dấu là đã cài đặt",
  "模型切号失败": "Cắt số mô hình không thành công",
  "模型名按本地": "Tên mẫu theo địa phương",
  "模型映射兜底": "Lập bản đồ mô hình chi tiết",
  "模型额度列表": "Danh sách hạn ngạch mẫu",
  "模式已合并到": "Lược đồ đã được hợp nhất thành",
  "正在交换令牌": "Trao đổi token",
  "此时实测累加": "Tại thời điểm này, số đo tích lũy thực tế",
  "每行一个邮箱": "Một hộp thư trên mỗi dòng",
  "永远沉到最底": "mãi chìm xuống đáy",
  "永远跟随此号": "Luôn theo dõi tài khoản này",
  "没命中映射时": "Khi bản đồ bị bỏ lỡ",
  "海外高速推理": "Lý luận tốc độ cao ở nước ngoài",
  "点击复制完整": "Bấm vào để sao chép hoàn tất",
  "点击复制账号": "Bấm để sao chép tài khoản",
  "点击查看明细": "Nhấn vào đây để xem chi tiết",
  "烧掉的是哪条": "Cái nào đã bị đốt cháy?",
  "环境变量配置": "Cấu hình biến môi trường",
  "用此账号覆盖": "Bảo hiểm bằng tài khoản này",
  "用账号名区分": "Phân biệt theo tên tài khoản",
  "百炼开放平台": "Nền tảng mở Bailian",
  "的样本被丢弃": "mẫu đã bị loại bỏ",
  "的窗口拉回满": "Cửa sổ được kéo trở lại đầy đủ",
  "的第三方中转": "chuyển nhượng bên thứ ba",
  "监听代理切号": "Giám sát chuyển đổi số đại lý",
  "监听所有网卡": "Giám sát tất cả các card mạng",
  "目标账号异常": "Tài khoản mục tiêu không bình thường",
  "确认切换失败": "Xác nhận lỗi chuyển đổi",
  "确认删除账号": "Xác nhận xóa tài khoản",
  "确认删除路由": "Xác nhận xóa tuyến đường",
  "等级动态返回": "Mức độ hoàn trả năng động",
  "等返回金额的": "Đang chờ số tiền hoàn lại",
  "简单按小时桶": "Xô đơn giản theo giờ",
  "类账号现在按": "Tài khoản lớp bây giờ nhấn",
  "网络请求失败": "Yêu cầu mạng không thành công",
  "自动复制失败": "Sao chép tự động không thành công",
  "自动识别格式": "Tự động nhận dạng định dạng",
  "自定义中转站": "Trạm trung chuyển tùy chỉnh",
  "订阅号可绑定": "Tài khoản đăng ký có thể bị ràng buộc",
  "让用户自己选": "Cho phép người dùng lựa chọn",
  "记下当前列表": "Ghi lại danh sách hiện tại",
  "记得保存设置": "Nhớ lưu cài đặt",
  "请先核对记录": "Vui lòng kiểm tra hồ sơ trước",
  "负责隐藏弹窗": "Chịu trách nhiệm ẩn cửa sổ bật lên",
  "账号今天到期": "Tài khoản hết hạn hôm nay",
  "账号导入文件": "Tệp nhập tài khoản",
  "账号已被封禁": "Tài khoản đã bị cấm",
  "超过该阈值时": "Khi vượt quá ngưỡng này",
  "足够让上一轮": "đủ để thực hiện vòng cuối cùng",
  "辅助工具函数": "Chức năng trợ giúp",
  "这将尝试移除": "Điều này sẽ cố gắng loại bỏ",
  "远程连接需要": "Yêu cầu kết nối từ xa",
  "选择中转服务": "Chọn dịch vụ relay/API",
  "选择目标账号": "Chọn tài khoản mục tiêu",
  "选择绑定账号": "Chọn ràng buộc tài khoản",
  "选预设自动填": "Chọn tự động điền mặc định",
  "通过代理连接": "Kết nối qua proxy",
  "避免偷扣余额": "Tránh bí mật khấu trừ số dư của bạn",
  "避免请求卡死": "Tránh yêu cầu bị mắc kẹt",
  "部分模型当前": "Một số mẫu hiện nay",
  "配合期间代理": "Đại lý trong quá trình hợp tác",
  "配额上限估算": "Ước tính giới hạn hạn ngạch",
  "配额用控制台": "Bảng điều khiển hạn ngạch",
  "里的监听会走": "Màn hình bên trong sẽ hoạt động",
  "重新加载设置": "Tải lại cài đặt",
  "量化误差最小": "Lỗi lượng tử hóa tối thiểu",
  "链接里携带的": "mang trong liên kết",
  "需要重新登录": "Cần đăng nhập lại",
  "首次请求自动": "Yêu cầu đầu tiên tự động",
  "默认优先显示": "Hiển thị đầu tiên theo mặc định",
  "默认自动探测": "Tự động phát hiện mặc định",
  "一条可用的": "một cái có sẵn",
  "上游会返回": "Ngược dòng sẽ trở lại",
  "上游已创建": "Thượng nguồn đã được tạo",
  "不在这里做": "Chưa xong ở đây",
  "不带尾斜杠": "không có dấu gạch chéo",
  "不特殊处理": "Không có sự đối xử đặc biệt",
  "不覆盖现有": "Không ghi đè lên hiện có",
  "个使用额度": "hạn ngạch sử dụng",
  "中转站主页": "Trang chủ trạm trung chuyển",
  "之后按固定": "Sau đó nhấn cố định",
  "也就是用户": "Tức là người dùng",
  "从仓库发现": "Tìm thấy từ kho",
  "从官方导入": "Nhập khẩu chính hãng",
  "代理出口在": "Đại lý xuất khẩu vào",
  "代理已停止": "Đại lý đã dừng",
  "代理已启动": "Đại lý đã bắt đầu",
  "代理未启动": "Đại lý chưa được bắt đầu",
  "代理运行中": "Đại lý đang chạy",
  "以应用新的": "áp dụng mới",
  "任一额度桶": "Bất kỳ nhóm hạn ngạch nào",
  "估算误差大": "Sai số ước lượng lớn",
  "余额走自家": "Giữ cân bằng ở nhà",
  "使用账号数": "Số tài khoản đã sử dụng",
  "保存后可在": "Sau khi lưu, bạn có thể",
  "保存后生效": "Có hiệu lực sau khi lưu",
  "保存并刷新": "Lưu và làm mới",
  "保存设置后": "Sau khi lưu cài đặt",
  "关闭代理后": "Sau khi đóng proxy",
  "再消耗一次": "tiêu thụ lại",
  "初始化数据": "dữ liệu khởi tạo",
  "刷新后额度": "Số tiền sau khi làm mới",
  "刷新限额条": "Làm mới thanh giới hạn",
  "加新条目时": "Khi thêm các mục mới",
  "占位提示用": "Lời nhắc giữ chỗ",
  "厂商自家的": "Của riêng nhà sản xuất",
  "只用于查询": "Chỉ được sử dụng cho truy vấn",
  "后端会派发": "Phần phụ trợ sẽ gửi đi",
  "后自动刷新": "Tự động làm mới sau",
  "后自动重试": "Tự động thử lại sau",
  "后重拉一次": "Sau đó kéo lại",
  "含到期时间": "Bao gồm cả thời gian hết hạn",
  "周窗口模型": "mô hình cửa sổ hàng tuần",
  "地址和对应": "Địa chỉ và thư từ",
  "地址和模型": "địa chỉ và mô hình",
  "复制命令到": "Sao chép lệnh vào",
  "复制此链接": "Sao chép liên kết này",
  "多模型聚合": "Tổng hợp nhiều mô hình",
  "天邀请记录": "bản ghi lời mời ngày",
  "失效或封号": "Không hợp lệ hoặc bị chặn",
  "套餐待同步": "Gói được đồng bộ hóa",
  "如果有冲突": "nếu có xung đột",
  "安静地忽略": "lặng lẽ bỏ qua",
  "实际模型按": "Máy ép mẫu thực tế",
  "客户端发的": "Được gửi bởi khách hàng",
  "导入中转站": "Trạm trung chuyển nhập khẩu",
  "局域网可用": "Mạng LAN có sẵn",
  "局域网同步": "Đồng bộ hóa mạng LAN",
  "已刷新额度": "Hạn ngạch đã được làm mới",
  "已安装列表": "Danh sách đã cài đặt",
  "已断开链接": "Liên kết bị hỏng",
  "已自动切换": "Tự động chuyển đổi",
  "已自动填好": "Tự động điền vào",
  "带冲突检测": "Với phát hiện xung đột",
  "开启后监听": "Giám sát sau khi mở",
  "弹出确认框": "Hộp xác nhận bật lên",
  "当前正在跟": "Hiện đang theo dõi",
  "快账号先回": "Vui lòng trả lời bằng tài khoản của bạn trước",
  "或重试复制": "Hoặc thử sao chép lại",
  "手机锚只对": "Chỉ neo điện thoại di động",
  "手机锚生效": "Neo di động có hiệu lực",
  "手机锚绑定": "Liên kết neo di động",
  "持久化当前": "duy trì hiện tại",
  "按模型分布": "Phân bổ theo mô hình",
  "按模型聚合": "Tổng hợp theo mô hình",
  "按账号聚合": "Tổng hợp theo tài khoản",
  "按账号表格": "Theo hình thức tài khoản",
  "授权已失效": "Ủy quyền đã hết hạn",
  "文本解析成": "Văn bản được phân tích thành",
  "新仓库表单": "Mẫu kho mới",
  "无时间返回": "Không có thời gian để quay lại",
  "是权威来源": "là một nguồn có thẩm quyền",
  "最大那个算": "Cái lớn nhất được tính",
  "未获取数据": "Không nhận được dữ liệu",
  "本地已保存": "Đã lưu cục bộ",
  "样本数低于": "Số lượng mẫu ít hơn",
  "检测到官方": "Chính thức được phát hiện",
  "检测到封号": "Đã phát hiện tài khoản bị cấm",
  "模型映射用": "Để lập bản đồ mô hình",
  "模型映射表": "bảng ánh xạ mô hình",
  "次限额重置": "thiết lập lại giới hạn",
  "测试连通性": "Kiểm tra kết nối",
  "消耗了到期": "tiêu thụ hết hạn",
  "源逻辑参考": "tham chiếu logic nguồn",
  "火山方舟的": "hòm núi lửa",
  "点开一行看": "Click vào một hàng để xem",
  "点开周期看": "Bấm vào để xem chu kỳ",
  "焦点丢失由": "mất tập trung bởi",
  "用户只需贴": "Người dùng chỉ cần đăng",
  "用户自己填": "Người dùng tự điền vào",
  "登录已失效": "Đăng nhập đã hết hạn",
  "的历史条目": "mục lịch sử",
  "的滑动窗口": "cửa sổ trượt",
  "的登录状态": "Trạng thái đăng nhập",
  "的那个会话": "của cuộc trò chuyện đó",
  "目录移除该": "Xóa thư mục",
  "直接切换将": "Chuyển mạch trực tiếp sẽ",
  "看起来不像": "Trông không giống",
  "看起来太短": "trông quá ngắn",
  "端口已更新": "Cổng đã được cập nhật",
  "粘贴到下方": "Dán bên dưới",
  "统一映射成": "được ánh xạ thống nhất vào",
  "网页登录的": "Đăng nhập web",
  "解析并导入": "Phân tích và nhập",
  "订阅到期日": "Ngày hết hạn đăng ký",
  "订阅号有效": "Số thuê bao hợp lệ",
  "让用户看到": "Cho người dùng xem",
  "设置已保存": "Đã lưu cài đặt",
  "该账号已被": "Tài khoản này đã được",
  "请刷新额度": "Vui lòng làm mới hạn ngạch",
  "请展开查看": "Vui lòng mở rộng để xem",
  "请手动重载": "Vui lòng tải lại theo cách thủ công",
  "请求里复制": "Sao chép theo yêu cầu",
  "请重新登录": "Vui lòng đăng nhập lại",
  "账号保护线": "Đường dây bảo vệ tài khoản",
  "账号到期日": "Ngày hết hạn tài khoản",
  "账号已到期": "Tài khoản đã hết hạn",
  "账号已添加": "Tài khoản đã được thêm",
  "账号走专属": "Tài khoản độc quyền",
  "身份不匹配": "Nhận dạng không khớp",
  "转成我们的": "Chuyển đổi sang của chúng tôi",
  "过期前可用": "Có sẵn trước khi hết hạn",
  "还没有任何": "Chưa có cái nào cả",
  "远端账号数": "Số lượng tài khoản từ xa",
  "透传不替换": "Truyền trong suốt mà không cần thay thế",
  "避免只显示": "Tránh chỉ hiển thị",
  "那条会返回": "Cái nào sẽ trở lại",
  "都替换成它": "Thay thế tất cả bằng nó",
  "重置倒计时": "Đặt lại đếm ngược",
  "隐藏旧数据": "Ẩn dữ liệu cũ",
  "隐藏的条数": "Số mục ẩn",
  "需要在多家": "Cần phải ở nhiều địa điểm",
  "需重新登录": "Cần đăng nhập lại",
  "顶部标题栏": "thanh tiêu đề trên cùng",
  "额度已耗尽": "Hạn ngạch đã hết",
  "默认账号名": "Tên tài khoản mặc định",
  "一键使用": "Một cú nhấp chuột để sử dụng",
  "一键填入": "Một cú nhấp chuột để điền vào",
  "三方模型": "Mô hình bên thứ ba",
  "三级下钻": "Đi sâu vào cấp độ ba",
  "上游协议": "thỏa thuận thượng nguồn",
  "上游只懂": "Thượng nguồn chỉ hiểu",
  "不会修改": "Sẽ không sửa đổi",
  "不扣次数": "Không khấu trừ số lần",
  "不拉余额": "Không có số dư",
  "不是冲突": "Không phải là xung đột",
  "不杀进程": "Đừng giết quá trình",
  "不能为空": "không thể trống",
  "不设兜底": "Không che chắn",
  "专属端点": "Điểm cuối riêng tư",
  "业务分类": "Phân loại doanh nghiệp",
  "个人账号": "Tài khoản cá nhân",
  "个连字符": "dấu gạch nối",
  "中国订阅": "thuê bao Trung Quốc",
  "中转服务": "dịch vụ quá cảnh",
  "中转账号": "Tài khoản chuyển tuyến",
  "主动重置": "Thiết lập lại hoạt động",
  "也不会让": "Tôi cũng sẽ không để nó",
  "二次点击": "Nhấp chuột thứ hai",
  "交互处理": "xử lý tương tác",
  "今天到期": "Hết hạn hôm nay",
  "仓库管理": "quản lý kho",
  "代理出口": "Đại lý xuất khẩu",
  "代理开关": "chuyển đổi proxy",
  "代理控制": "Kiểm soát đại lý",
  "代理服务": "dịch vụ đại lý",
  "代理端口": "cổng proxy",
  "任务类型": "Loại nhiệm vụ",
  "优先尝试": "Hãy thử trước",
  "会显示在": "sẽ được hiển thị trong",
  "估算上限": "Giới hạn trên ước tính",
  "余额展示": "Hiển thị cân bằng",
  "余额查询": "Truy vấn số dư",
  "使用平台": "Sử dụng nền tảng",
  "使用时长": "Thời gian sử dụng",
  "供回头看": "vì nhìn lại",
  "保存失败": "Lưu không thành công",
  "保存设置": "Lưu cài đặt",
  "保鲜已关": "Giữ tươi đang tắt",
  "修复失败": "Sửa chữa không thành công",
  "修复成功": "Sửa chữa thành công",
  "修改端口": "Sửa đổi cổng",
  "免费限额": "giới hạn miễn phí",
  "全局代理": "đại lý toàn cầu",
  "全局统计": "thống kê toàn cầu",
  "全球聚合": "tổng hợp toàn cầu",
  "全部项目": "Tất cả dự án",
  "全量同步": "Đồng bộ hóa hoàn toàn",
  "共享密钥": "khóa chia sẻ",
  "关闭代理": "Tắt proxy",
  "兼容模式": "Chế độ tương thích",
  "内部已经": "Đã ở trong rồi",
  "准备就绪": "sẵn sàng",
  "出口照切": "giấy phép xuất khẩu",
  "分钟一轮": "vòng phút",
  "切号原因": "Lý do chuyển số",
  "切号后在": "Sau khi thay đổi số",
  "切号失败": "Chuyển đổi số không thành công",
  "切号日志": "Nhật ký chuyển số",
  "切号模式": "Chế độ cắt số",
  "切号次数": "Số lần cắt",
  "切号通知": "Thông báo chuyển số",
  "切换服务": "Chuyển đổi dịch vụ",
  "切换账号": "Chuyển tài khoản",
  "切换路径": "chuyển đổi đường dẫn",
  "初始加载": "tải ban đầu",
  "删除后该": "Sau khi xóa",
  "删除账号": "Xóa tài khoản",
  "删除路由": "Xóa tuyến đường",
  "到期日期": "Ngày hết hạn",
  "到期时间": "Thời gian hết hạn",
  "到点触发": "Kích hoạt đúng điểm",
  "刷新令牌": "mã thông báo làm mới",
  "刷新失败": "Làm mới không thành công",
  "刷新资格": "Làm mới bằng cấp",
  "刷新间隔": "khoảng thời gian làm mới",
  "前端尊重": "Sự tôn trọng từ phía trước",
  "前缀派生": "đạo hàm tiền tố",
  "剩余次数": "Số lần còn lại",
  "剩余额度": "số dư còn lại",
  "加载更多": "tải thêm",
  "加载用量": "Tải mức sử dụng",
  "单端执行": "thực hiện một đầu",
  "即将卸载": "Sẽ sớm được gỡ cài đặt",
  "即将重置": "Sắp đặt lại",
  "卸载失败": "Gỡ cài đặt không thành công",
  "原生路由": "Định tuyến gốc",
  "双栏布局": "Bố cục hai cột",
  "双行结构": "cấu trúc hàng đôi",
  "发现列表": "danh sách khám phá",
  "发现失败": "Khám phá không thành công",
  "发送邀请": "Gửi lời mời",
  "发邀账号": "Mời tài khoản",
  "取消切换": "Hủy chuyển đổi",
  "受邀邮箱": "Email được mời",
  "只适用于": "chỉ áp dụng cho",
  "可发一句": "Bạn có thể gửi một câu",
  "合在一起": "cùng nhau",
  "同时写入": "viết đồng thời",
  "同时支持": "Hỗ trợ cả hai",
  "同时生效": "Có hiệu lực đồng thời",
  "同步失败": "Đồng bộ hóa không thành công",
  "同步完成": "Đồng bộ hóa đã hoàn tất",
  "同步所有": "Đồng bộ hóa tất cả",
  "同步操作": "Hoạt động đồng bộ",
  "同步状态": "Trạng thái đồng bộ hóa",
  "同步磁盘": "Đồng bộ đĩa",
  "后台保活": "nền giữ nguyên",
  "后台服务": "Dịch vụ nền",
  "后端任务": "Nhiệm vụ phụ trợ",
  "后端内置": "Tích hợp sẵn phần phụ trợ",
  "向下取整": "Làm tròn xuống",
  "启动代理": "Bắt đầu đại lý",
  "启动失败": "Khởi động không thành công",
  "启动监听": "Bắt đầu nghe",
  "周期保鲜": "Chu kỳ làm mới",
  "周期列表": "danh sách thời gian",
  "命中次数": "Số lượt truy cập",
  "嗅探窗口": "cửa sổ đánh hơi",
  "因为此刻": "bởi vì tại thời điểm này",
  "国际订阅": "Thuê bao quốc tế",
  "均可修改": "Tất cả đều có thể được sửa đổi",
  "均走代理": "Tất cả đại lý",
  "填写凭据": "Điền thông tin xác thực",
  "失败的话": "Nếu nó thất bại",
  "字符即可": "nhân vật",
  "字节上限": "Giới hạn byte",
  "字节跳动": "ByteDance",
  "安全可信": "An toàn và đáng tin cậy",
  "安装失败": "Cài đặt không thành công",
  "完全分开": "hoàn toàn riêng biệt",
  "实测累加": "Tích lũy số đo thực tế",
  "实验特性": "Tính chất thí nghiệm",
  "宽松校验": "Tổng kiểm tra thoải mái",
  "对象数组": "mảng đối tượng",
  "导入失败": "Nhập không thành công",
  "导出失败": "Xuất không thành công",
  "导出成功": "Xuất thành công",
  "导航菜单": "Trình đơn điều hướng",
  "封号事件": "Sự kiện cấm tài khoản",
  "将被消耗": "sẽ được tiêu thụ",
  "小时窗口": "cửa sổ giờ",
  "小时聚合": "Tổng hợp hàng giờ",
  "小时配额": "hạn ngạch hàng giờ",
  "工作模式": "chế độ làm việc",
  "工作账号": "Tài khoản công việc",
  "已切换到": "Đã chuyển sang",
  "已链接到": "Liên kết với",
  "开始授权": "Bắt đầu ủy quyền",
  "开放平台": "nền tảng mở",
  "强制冷切": "Cắt nguội cưỡng bức",
  "当前模型": "mô hình hiện tại",
  "当前没有": "Hiện tại không có",
  "当前活跃": "Hiện đang hoạt động",
  "当前绑定": "ràng buộc hiện tại",
  "当前账号": "Tài khoản hiện tại",
  "形式不同": "Các hình thức khác nhau",
  "彻底删除": "Xóa hoàn toàn",
  "快速链接": "Liên kết nhanh",
  "忽略空行": "bỏ qua dòng trống",
  "成功后用": "Sử dụng sau khi thành công",
  "所有文件": "Tất cả các tập tin",
  "所有次数": "mọi lúc",
  "手动启动": "Khởi động thủ công",
  "手动输入": "Nhập thủ công",
  "手工拉取": "Kéo bằng tay",
  "手工维护": "Bảo trì thủ công",
  "手机验证": "Xác minh điện thoại di động",
  "批量导入": "Nhập hàng loạt",
  "把最新的": "đặt cái mới nhất",
  "拉取合并": "Kéo hợp nhất",
  "拒绝请求": "Từ chối yêu cầu",
  "按量付费": "Trả theo mức sử dụng",
  "授权成功": "Ủy quyền thành công",
  "授权链接": "Liên kết ủy quyền",
  "接口时用": "Dùng cho giao diện",
  "接口返回": "trở lại giao diện",
  "推荐账号": "Tài khoản được đề xuất",
  "推送全部": "đẩy tất cả",
  "推送失败": "Đẩy không thành công",
  "搜索账号": "Tìm kiếm tài khoản",
  "搜索邮箱": "Tìm kiếm hộp thư",
  "摘要卡片": "thẻ tóm tắt",
  "操作失败": "Thao tác không thành công",
  "故障修复": "sửa lỗi",
  "数据老于": "Dữ liệu cũ hơn",
  "文心一言": "Wenxinyiyan",
  "方便识别": "Dễ dàng xác định",
  "方式重启": "khởi động lại chế độ",
  "无可重置": "Không đặt lại",
  "无法读取": "Không thể đọc",
  "无法重置": "Không thể đặt lại",
  "无需切换": "Không cần phải chuyển đổi",
  "无需权限": "Không cần sự cho phép",
  "日期异常": "Ngày bất thường",
  "早期数据": "dữ liệu ban đầu",
  "早期没记": "Tôi đã không nhớ nó trong những ngày đầu",
  "时分配的": "được phân bổ đúng thời hạn",
  "时只准备": "Chỉ cần chuẩn bị",
  "时间上限": "giới hạn thời gian",
  "时间序列": "chuỗi thời gian",
  "明确支持": "được hỗ trợ rõ ràng",
  "是否继续": "Bạn có muốn tiếp tục không?",
  "智能重试": "Thử lại thông minh",
  "暂不适配": "Chưa phù hợp",
  "暂存目标": "mục tiêu dàn dựng",
  "暂无推荐": "Chưa có đề xuất nào",
  "暂无数据": "Chưa có dữ liệu",
  "暂无账号": "Chưa có tài khoản",
  "暗黑护眼": "Bảo vệ mắt tối",
  "更新设置": "Cập nhật cài đặt",
  "更新账号": "Cập nhật tài khoản",
  "最后更新": "cập nhật lần cuối",
  "最多一个": "nhiều nhất là một",
  "最早在前": "sớm nhất trước tiên",
  "最近尝试": "những nỗ lực gần đây",
  "最近成功": "thành công gần đây",
  "最近结果": "kết quả gần đây",
  "月之暗面": "Kimi",
  "未知账号": "Tài khoản không xác định",
  "本地代理": "đại lý địa phương",
  "本地推理": "lý luận cục bộ",
  "本机不跑": "Máy không chạy",
  "本次奖励": "Phần thưởng này",
  "机器可把": "Máy có thể xử lý được",
  "检查代理": "Kiểm tra proxy",
  "模型兜底": "Người mẫu kể chuyện",
  "模型分布": "Phân phối mô hình",
  "模型列表": "Danh sách người mẫu",
  "模型通过": "Mô hình đã được thông qua",
  "次数未知": "thời gian không xác định",
  "正在使用": "đang được sử dụng",
  "正在切换": "Chuyển đổi",
  "正在启动": "Bắt đầu",
  "正在扫描": "Đang quét",
  "正在重置": "Đặt lại",
  "每格显示": "Hiển thị trên mỗi lưới",
  "没有匹配": "không có trận đấu",
  "没有账号": "Không có tài khoản",
  "没有这个": "không cái này",
  "活动范围": "Phạm vi hoạt động",
  "测试连接": "kết nối thử nghiệm",
  "添加中转": "Thêm relay/API",
  "添加账号": "Thêm tài khoản",
  "添加路由": "Thêm tuyến đường",
  "清除日期": "Xóa ngày",
  "火山方舟": "Volcengine Ark",
  "点击修改": "Bấm để sửa đổi",
  "点击修正": "Bấm để sửa",
  "点击刷新": "Bấm để làm mới",
  "点击打开": "Bấm để mở",
  "状态为准": "Tùy thuộc vào trạng thái",
  "状态失败": "trạng thái không thành công",
  "环境变量": "biến môi trường",
  "生成失败": "Xây dựng không thành công",
  "用快照里": "Sử dụng ảnh chụp nhanh",
  "用户参考": "Tài liệu tham khảo của người dùng",
  "用户可改": "Người dùng có thể thay đổi",
  "用量统计": "Thống kê sử dụng",
  "界面外观": "Giao diện xuất hiện",
  "界面配色": "Phối màu giao diện",
  "登录状态": "Trạng thái đăng nhập",
  "登录账号": "Đăng nhập tài khoản",
  "登录身份": "Danh tính đăng nhập",
  "百度千帆": "Baidu Qianfan",
  "的第三方": "bên thứ ba",
  "监听端口": "cổng nghe",
  "目标账号": "tài khoản mục tiêu",
  "直接通过": "vượt qua trực tiếp",
  "确认卸载": "Xác nhận gỡ cài đặt",
  "确认覆盖": "Xác nhận phạm vi bảo hiểm",
  "磁盘落后": "lag đĩa",
  "神马中转": "quá cảnh Shenma",
  "立即修复": "Sửa ngay bây giờ",
  "立即同号": "Cùng một số ngay lập tức",
  "立即登录": "Đăng nhập ngay bây giờ",
  "立即重启": "Khởi động lại ngay bây giờ",
  "立即重置": "Đặt lại ngay bây giờ",
  "等价于旧": "tương đương với cũ",
  "类账号在": "Tài khoản lớp học trong",
  "精确累加": "Tích lũy chính xác",
  "系列为主": "Chủ yếu là loạt",
  "系统通知": "Thông báo hệ thống",
  "终止所有": "chấm dứt tất cả",
  "终止进程": "Chấm dứt quá trình",
  "绑定地址": "Địa chỉ ràng buộc",
  "绑定失败": "Ràng buộc không thành công",
  "绑定账号": "Liên kết tài khoản",
  "统计卡片": "Thẻ thống kê",
  "编程套餐": "Gói lập trình",
  "编辑备注": "Ghi chú của biên tập viên",
  "聚合中转": "Chuyển tổng hợp",
  "腾讯混元": "Tencent Hunyuan",
  "自动刷新": "Tự động làm mới",
  "自动同号": "Tự động cùng số",
  "自动同步": "Tự động đồng bộ hóa",
  "自动填好": "Tự động điền vào",
  "自动导入": "Nhập tự động",
  "自动探测": "tự động phát hiện",
  "自动迁移": "Di chuyển tự động",
  "自动重载": "tự động tải lại",
  "行为一致": "Cư xử nhất quán",
  "行内标签": "thẻ nội tuyến",
  "解析有效": "Phân tích cú pháp là hợp lệ",
  "解除失败": "Phát hành không thành công",
  "触发一次": "kích hoạt một lần",
  "订阅号走": "Số đăng ký đi",
  "订阅密钥": "Khóa đăng ký",
  "订阅服务": "Dịch vụ đăng ký",
  "订阅类型": "Loại đăng ký",
  "识别条件": "Điều kiện nhận dạng",
  "详情弹窗": "Cửa sổ bật lên chi tiết",
  "请求超时": "Yêu cầu hết thời gian",
  "调度间隔": "Khoảng thời gian lập kế hoạch",
  "账号信息": "Thông tin tài khoản",
  "账号名称": "Tên tài khoản",
  "账号总数": "Tổng số tài khoản",
  "账号显示": "Hiển thị tài khoản",
  "账号管理": "Quản lý tài khoản",
  "账号还有": "Vẫn còn một tài khoản",
  "费用趋势": "xu hướng chi phí",
  "趋势数据": "dữ liệu xu hướng",
  "身份匹配": "So khớp danh tính",
  "身份在线": "Nhận dạng trực tuyến",
  "过期返回": "Trả lại sau khi hết hạn",
  "过滤胶囊": "viên nang lọc",
  "返回选择": "Quay lại lựa chọn",
  "这里再弹": "Chơi lại ở đây",
  "进程管理": "Quản lý quy trình",
  "选择会话": "Chọn phiên",
  "通用中转": "Quá cảnh phổ quát",
  "通知设置": "Cài đặt thông báo",
  "避免叠加": "tránh lớp phủ",
  "避免误导": "tránh gây hiểu lầm",
  "邀请使用": "Mời sử dụng",
  "邀请弹窗": "Cửa sổ bật lên lời mời",
  "那头超时": "Hết thời gian ở đầu bên kia",
  "都能识别": "Tất cả đều có thể được công nhận",
  "配额偏低": "Hạn ngạch thấp",
  "配额充足": "Đủ hạn ngạch",
  "配额状态": "trạng thái hạn ngạch",
  "里在飞的": "Nó đang bay",
  "重新查询": "Truy vấn lại",
  "重置失败": "Đặt lại không thành công",
  "重置成功": "Đặt lại thành công",
  "重置时间": "đặt lại thời gian",
  "重置未知": "thiết lập lại không xác định",
  "重置表单": "Đặt lại biểu mẫu",
  "锁在哪号": "Số nào là khóa?",
  "阶跃星辰": "Bước sao",
  "阿里魔搭": "Alibaba ModelScope",
  "顶层一格": "Hàng đầu",
  "额度余额": "Cân bằng hạn ngạch",
  "额度桶为": "Nhóm hạn ngạch là",
  "首条消息": "Tin nhắn đầu tiên",
  "高级设置": "Cài đặt nâng cao",
  "默认模型": "Mô hình mặc định",
  "一把梭": "Xe đưa đón",
  "一类的": "một loại",
  "上游已": "thượng nguồn có",
  "上游懂": "Thượng lưu hiểu",
  "下半部": "phần dưới",
  "下所有": "Tải xuống tất cả",
  "不一致": "không nhất quán",
  "不偷换": "Không trao đổi bí mật",
  "不再经": "Không còn nữa",
  "不展示": "Không hiển thị",
  "不平均": "không đồng đều",
  "不影响": "không ảnh hưởng",
  "不打折": "Không giảm giá",
  "不拉取": "Đừng kéo",
  "不掉线": "Không bị rơi",
  "不认识": "không biết",
  "与普通": "với bình thường",
  "个账号": "tài khoản",
  "个邮箱": "hộp thư",
  "中转站": "Relay",
  "之前是": "trước đây",
  "也支持": "Cũng hỗ trợ",
  "仅本机": "Máy này chỉ",
  "代理开": "Khai trương đại lý",
  "以确认": "để xác nhận",
  "仪表盘": "Tổng quan",
  "优刻得": "UCloud",
  "但使用": "nhưng sử dụng",
  "但同步": "nhưng đồng bộ",
  "但消耗": "nhưng tiêu thụ",
  "侧提供": "Bên cung cấp",
  "保存中": "Đang lưu",
  "保活由": "Giữ sự sống bằng cách",
  "修复中": "Đang sửa chữa",
  "全覆盖": "bảo hiểm đầy đủ",
  "全部走": "Tất cả đi",
  "兼容的": "tương thích",
  "分钟前": "phút trước",
  "创建于": "Được tạo ở",
  "剩余为": "Phần còn lại là",
  "加载中": "Đang tải",
  "双协议": "thỏa thuận kép",
  "发送中": "Đang gửi",
  "只暴露": "chỉ tiếp xúc",
  "可修改": "Có thể sửa đổi",
  "可能是": "Có lẽ",
  "同步中": "Đồng bộ hóa",
  "同步到": "Đồng bộ hóa với",
  "后重拉": "Kéo lại",
  "后重置": "đặt lại sau",
  "启动中": "Bắt đầu",
  "周周期": "Chu kỳ hàng tuần",
  "周配额": "Hạn ngạch hàng tuần",
  "周限额": "Giới hạn hàng tuần",
  "命中率": "tỷ lệ trúng",
  "命中过": "Đánh",
  "填写此": "điền vào cái này",
  "处理中": "Xử lý",
  "复制中": "Sao chép",
  "天到期": "ngày hết hạn",
  "天窗口": "cửa sổ bầu trời",
  "失败项": "mục thất bại",
  "完成且": "hoàn thành và",
  "实验性": "thực nghiệm",
  "客户端": "khách hàng",
  "对齐到": "Căn chỉnh để",
  "导入中": "Đang nhập",
  "将本机": "Đặt máy này",
  "小时前": "giờ trước",
  "展示用": "để trưng bày",
  "工作区": "không gian làm việc",
  "已上传": "Đã tải lên",
  "已停止": "Đã dừng",
  "已关闭": "Đã tắt",
  "已删除": "Đã xóa",
  "已卸载": "Đã gỡ cài đặt",
  "已合并": "Đã hợp nhất",
  "已启用": "Đã bật",
  "已复制": "Đã sao chép",
  "已失效": "Hết hạn",
  "已安装": "Đã cài đặt",
  "已封号": "Tài khoản đã bị chặn",
  "已并入": "Đã kết hợp",
  "已开启": "Đã bật rồi",
  "已忽略": "Đã bỏ qua",
  "已打开": "Đã mở",
  "已添加": "Đã thêm",
  "已禁用": "Tàn tật",
  "已获取": "thu được",
  "已过期": "Hết hạn",
  "已重置": "Cài lại",
  "已链接": "Đã liên kết",
  "并落库": "Và ghé vào thư viện",
  "建议填": "Nên điền vào",
  "开启后": "Sau khi mở",
  "强一致": "Tính nhất quán mạnh mẽ",
  "当前号": "Số hiện tại",
  "当前用": "hiện đang được sử dụng",
  "当账号": "Khi tài khoản",
  "待刷新": "Để được làm mới",
  "必须与": "Phải ở cùng",
  "必须以": "Phải là",
  "必须用": "Phải sử dụng",
  "总容量": "tổng công suất",
  "总花费": "tổng chi phí",
  "总费用": "tổng chi phí",
  "我们用": "Chúng tôi sử dụng",
  "我们走": "đi thôi",
  "手动填": "Điền thủ công",
  "手机在": "Điện thoại di động là",
  "手机锚": "mỏ neo di động",
  "打开时": "khi mở",
  "执行中": "Đang thực hiện",
  "扫描中": "Đang quét",
  "把错误": "đặt lỗi",
  "拿到新": "nhận được cái mới",
  "持久化": "kiên trì",
  "按小时": "hàng giờ",
  "按模型": "theo mô hình",
  "按账号": "Theo tài khoản",
  "授权后": "Sau khi ủy quyền",
  "授权码": "Mã ủy quyền",
  "控制台": "bảng điều khiển",
  "推出该": "khởi động",
  "推送到": "đẩy tới",
  "提交中": "Đang gửi",
  "改为从": "Thay đổi từ",
  "新字段": "lĩnh vực mới",
  "新账号": "tài khoản mới",
  "旋转走": "Quay đi",
  "无描述": "Không có mô tả",
  "无数据": "Không có dữ liệu",
  "旧任务": "nhiệm vụ cũ",
  "时切号": "số thời gian",
  "时显示": "hiển thị thời gian",
  "映射到": "ánh xạ tới",
  "映射表": "bảng ánh xạ",
  "是中转": "Đó là một quá cảnh",
  "是整数": "là một số nguyên",
  "未成功": "không thành công",
  "未提供": "Không được cung cấp",
  "未绑定": "Không bị ràng buộc",
  "未设置": "chưa được đặt",
  "未链接": "Không được liên kết",
  "本机管": "Quản lý địa phương",
  "条规则": "quy tắc",
  "条邀请": "lời mời",
  "查询中": "Truy vấn",
  "查询近": "Truy vấn gần đây",
  "标记的": "đánh dấu",
  "桌面版": "Phiên bản máy tính để bàn",
  "检测到": "phát hiện",
  "模型按": "Máy ép mẫu",
  "模式由": "Mẫu bao gồm",
  "次请求": "yêu cầu",
  "添加中": "Thêm",
  "状态条": "thanh trạng thái",
  "玛瑙绿": "mã não xanh",
  "用户在": "Người dùng đang ở",
  "用户点": "điểm người dùng",
  "的实际": "thật sự",
  "的模型": "người mẫu",
  "的规则": "quy tắc",
  "的那条": "cái một",
  "的麻烦": "rắc rối",
  "直接当": "trực tiếp như",
  "看全量": "Xem số lượng đầy đủ",
  "端一致": "Nhất quán",
  "端发的": "cuối đời",
  "等只懂": "Chỉ cần chờ đợi và hiểu",
  "等金额": "số tiền bằng nhau",
  "纯文本": "văn bản thuần túy",
  "终止中": "Chấm dứt",
  "经典蓝": "màu xanh cổ điển",
  "绑定表": "bảng ràng buộc",
  "背景色": "màu nền",
  "自定义": "Tùy chỉnh",
  "被节流": "bị điều tiết",
  "被限流": "Bị hạn chế",
  "订阅号": "Số đăng ký",
  "订阅类": "Lớp đăng ký",
  "让上面": "để đỉnh cao",
  "该账号": "Tài khoản này",
  "请求数": "Số lượng yêu cầu",
  "请粘贴": "Vui lòng dán",
  "请输入": "Vui lòng nhập",
  "账号于": "Tài khoản tại",
  "账号名": "Tên tài khoản",
  "账号走": "Tài khoản đã biến mất",
  "走专属": "Đi độc quyền",
  "趋势图": "Biểu đồ xu hướng",
  "跑文档": "Chạy tài liệu",
  "运行中": "Đang chạy",
  "返回的": "trả lại",
  "这里用": "Được sử dụng ở đây",
  "这里的": "Đây là",
  "进度条": "thanh tiến trình",
  "进行中": "đang tiến hành",
  "选一个": "chọn một",
  "选预设": "Chọn mặc định",
  "里逐个": "từng cái một",
  "重置中": "Đặt lại",
  "重试中": "Đang thử lại",
  "金额型": "Loại số tiền",
  "锁定在": "bị nhốt trong",
  "问候语": "lời chào",
  "防误触": "Chống chạm vô tình",
  "阿里云": "Alibaba Cloud",
  "需要在": "cần phải ở trong",
  "需重登": "Cần đăng nhập lại",
  "一致": "nhất quán",
  "三方": "Bên thứ ba",
  "三色": "ba màu",
  "上层": "lớp trên",
  "上月": "tháng trước",
  "上次": "lần trước",
  "下次": "lần sau",
  "不写": "Đừng viết",
  "不动": "Không di chuyển",
  "不变": "không thay đổi",
  "不同": "khác biệt",
  "不含": "Không chứa",
  "不填": "Để trống",
  "不是": "KHÔNG",
  "不查": "Đừng kiểm tra",
  "不被": "không được",
  "不调": "Lạc điệu",
  "个新": "mới",
  "中位": "ở giữa",
  "中转": "Relay",
  "为准": "tùy thuộc vào",
  "主力": "Lực lượng chính",
  "主页": "Trang chủ",
  "也用": "Cũng được sử dụng",
  "也跟": "Cũng theo dõi",
  "互斥": "loại trừ lẫn nhau",
  "仅刷": "chỉ chải",
  "今天": "Hôm nay",
  "仍从": "Vẫn từ",
  "仍以": "Vẫn với",
  "从未": "không bao giờ",
  "仓库": "nhà kho",
  "代理": "Proxy",
  "会话": "phiên họp",
  "余额": "Sự cân bằng",
  "你好": "Xin chào",
  "使用": "sử dụng",
  "例如": "Ví dụ",
  "保存": "Lưu",
  "保活": "giữ sống",
  "保留": "dự trữ",
  "修复": "Sửa chữa",
  "修改": "Ôn lại",
  "偏小": "Bé nhỏ",
  "停在": "dừng lại ở",
  "健康": "khỏe mạnh",
  "先去": "Đi trước",
  "兑现": "tiền mặt",
  "全价": "giá đầy đủ",
  "关于": "Về",
  "关闭": "Đóng",
  "其它": "khác",
  "兼容": "tương thích",
  "内置": "tích hợp sẵn",
  "写入": "viết",
  "决定": "Quyết định",
  "冷却": "hạ nhiệt",
  "出来": "đi ra ngoài",
  "分布": "phân phối",
  "分流": "Chuyển hướng",
  "分钟": "phút",
  "切到": "Cắt thành",
  "切换": "công tắc",
  "刚刚": "chỉ",
  "删除": "Xóa",
  "到期": "trưởng thành",
  "刷新": "Làm mới",
  "前缀": "tiền tố",
  "剩余": "Còn lại",
  "动态": "năng động",
  "包含": "Bao gồm",
  "单位": "đơn vị",
  "即可": "Thế thôi",
  "卸载": "gỡ cài đặt",
  "厂商": "nhà sản xuất",
  "历史": "lịch sử",
  "原因": "lý do",
  "原理": "nguyên tắc",
  "原生": "Tự nhiên",
  "反推": "Đẩy lùi",
  "反查": "Phản điều tra",
  "发现": "Phát hiện",
  "取消": "Hủy",
  "可选": "Không bắt buộc",
  "合并": "hợp nhất",
  "合成": "tổng hợp",
  "同名": "Cùng tên",
  "同步": "đồng bộ",
  "同路": "đi cùng một con đường",
  "名称": "Tên",
  "后端": "phía sau",
  "否则": "nếu không thì",
  "启动": "Khởi động",
  "启用": "Bật",
  "周期": "xe đạp",
  "命中": "đánh",
  "四段": "bốn phần",
  "回退": "quay lại",
  "国内": "nội địa",
  "地址": "Địa chỉ",
  "基于": "dựa trên",
  "处理": "đối phó với",
  "备注": "Nhận xét",
  "复制": "Sao chép",
  "天前": "ngày trước",
  "天后": "nữ hoàng thiên đường",
  "失效": "Không hợp lệ",
  "失败": "Thất bại",
  "奖励": "phần thưởng",
  "子集": "tập hợp con",
  "字符": "tính cách",
  "守卫": "canh gác",
  "安装": "Cài đặt",
  "完成": "Hoàn tất",
  "官方": "chính thức",
  "导入": "Nhập",
  "导出": "Xuất",
  "封号": "tiêu đề",
  "封禁": "lệnh cấm",
  "小时": "Giờ",
  "小米": "MiMo",
  "工作": "Công việc",
  "已与": "Đã có với",
  "已写": "bằng văn bản",
  "已将": "Đã",
  "已选": "Đã chọn",
  "平均": "trung bình",
  "年龄": "tuổi",
  "并以": "Và với",
  "应用": "ứng dụng",
  "开启": "Bật",
  "开头": "sự khởi đầu",
  "开始": "bắt đầu",
  "当前": "Hiện tại",
  "形如": "có hình dạng như",
  "形式": "hình thức",
  "徽章": "huy hiệu",
  "心跳": "nhịp tim",
  "必填": "Yêu cầu",
  "快照": "Ảnh chụp nhanh",
  "总量": "tổng số tiền",
  "成功": "Thành công",
  "或周": "hoặc tuần",
  "所属": "Thuộc về",
  "所有": "tất cả",
  "手动": "Thủ công",
  "手机": "điện thoại di động",
  "拉到": "kéo đến",
  "拦截": "chặn",
  "挂到": "chờ đã",
  "指定": "Chỉ định",
  "指针": "con trỏ",
  "按天": "theo ngày",
  "按量": "Theo số lượng",
  "按钮": "cái nút",
  "授权": "Ủy quyền",
  "探测": "phát hiện",
  "接口": "giao diện",
  "推荐": "Khuyến nghị",
  "推送": "xô",
  "提示": "gợi ý",
  "搜索": "Tìm kiếm",
  "操作": "vận hành",
  "改用": "Sử dụng thay thế",
  "故意": "cố ý",
  "整个": "toàn bộ",
  "新增": "Mới",
  "旧的": "cũ",
  "时会": "cuộc họp thời gian",
  "时按": "nút thời gian",
  "时间": "thời gian",
  "明细": "Chi tiết",
  "昨天": "Hôm qua",
  "显示": "trình diễn",
  "智谱": "GLM",
  "暴露": "để lộ ra",
  "更换": "thay thế",
  "更新": "gia hạn",
  "替换": "thay thế",
  "最多": "hầu hết",
  "最近": "gần đây",
  "服务": "Phục vụ",
  "未知": "Không xác định",
  "末次": "Lần trước",
  "本地": "Cục bộ",
  "本机": "máy cục bộ",
  "权限": "Quyền",
  "来源": "nguồn",
  "来自": "từ",
  "样本": "vật mẫu",
  "格式": "Định dạng",
  "检查": "nghiên cứu",
  "检测": "Kiểm tra",
  "模型": "Mô hình",
  "模式": "người mẫu",
  "正常": "Bình thường",
  "每号": "Mỗi số",
  "每行": "mỗi dòng",
  "比如": "Ví dụ",
  "没有": "KHÔNG",
  "注意": "Để ý",
  "注释": "Bình luận",
  "活跃": "tích cực",
  "流程": "quá trình",
  "海外": "ở nước ngoài",
  "消耗": "tiêu thụ",
  "添加": "Thêm",
  "清空": "Thông thoáng",
  "火山": "núi lửa",
  "点击": "nhấp chuột",
  "热切": "háo hức",
  "状态": "Trạng thái",
  "独立": "độc lập",
  "生成": "phát ra",
  "用于": "dùng cho",
  "用户": "người dùng",
  "用量": "Mức sử dụng",
  "留空": "Để trống",
  "登录": "Đăng nhập",
  "百度": "Baidu",
  "的行": "hàng",
  "直连": "kết nối trực tiếp",
  "真的": "thực tế",
  "确认": "Xác nhận",
  "磁盘": "đĩa",
  "移除": "Di dời",
  "窗口": "cửa sổ",
  "端口": "hải cảng",
  "端慢": "Cổng chậm",
  "等价": "sự tương đương",
  "粘贴": "Dán",
  "系列": "loạt",
  "累计": "Tổng cộng",
  "终端": "phần cuối",
  "绑定": "ràng buộc",
  "绕过": "đường vòng",
  "统计": "Thống kê",
  "缓存": "Bộ nhớ đệm",
  "网段": "đoạn mạng",
  "网络": "mạng",
  "翻译": "dịch",
  "耗尽": "kiệt sức",
  "聚合": "sự trùng hợp",
  "腾讯": "Tencent",
  "自动": "Tự động",
  "自家": "Trang chủ",
  "自建": "Tự xây dựng",
  "节省": "cứu",
  "花费": "tiêu",
  "若有": "Nếu vậy",
  "落后": "phía sau",
  "覆盖": "che phủ",
  "解析": "phân tích cú pháp",
  "解除": "Thang máy",
  "触发": "cò súng",
  "订阅": "Gói đăng ký",
  "设置": "Cài đặt",
  "说明": "minh họa",
  "请求": "Yêu cầu",
  "负责": "Chịu trách nhiệm",
  "账号": "Tài khoản",
  "费用": "trị giá",
  "趋势": "xu hướng",
  "跨过": "vượt qua",
  "路径": "con đường",
  "路由": "Định tuyến",
  "跳过": "nhảy qua",
  "身份": "danh tính",
  "转发": "Phía trước",
  "轮数": "Số vòng",
  "过期": "Hết hạn",
  "过滤": "lọc",
  "运行": "chạy",
  "还为": "cũng dành cho",
  "这是": "Đây là",
  "进程": "quá trình",
  "连接": "Kết nối",
  "适合": "Thích hợp",
  "通义": "Qwen",
  "通常": "nói chung là",
  "通用": "Phổ quát",
  "通知": "thông báo",
  "遇到": "gặp",
  "邮箱": "Thư",
  "配合": "hợp tác",
  "配置": "Cấu hình",
  "配额": "Hạn mức",
  "里的": "bên trong",
  "重启": "Khởi động lại",
  "重置": "Đặt lại",
  "重试": "Thử lại",
  "重载": "Quá tải",
  "鉴权": "Xác thực",
  "错误": "Lỗi",
  "闪退": "tai nạn",
  "限额": "giới hạn",
  "隔离": "sự cách ly",
  "需先": "Cần đầu tiên",
  "需用": "Cần thiết",
  "非空": "Không trống",
  "面板": "bảng điều khiển",
  "顶部": "đứng đầu",
  "预设": "Mặc định",
  "额度": "Hạn mức",
  "饼图": "biểu đồ hình tròn",
  "首次": "Đầu tiên",
  "魔搭": "ModelScope",
  "默认": "Mặc định",
  "分": "phút",
  "周": "tuần",
  "天": "ngày",
  "时": "giờ",
  "秒": "giây",
};

// Exact UI copy takes precedence over the legacy fragment dictionary. Fragment
// translation is retained only as a fallback for uncommon backend messages;
// exact copy avoids stiff combinations such as "cổng biển" for a network port.
const VI_EXACT: Record<string, string> = {
  "账号信息": "Tài khoản",
  "配额状态": "Hạn mức còn lại",
  "同步/保活": "Đồng bộ và duy trì phiên",
  "操作": "Thao tác",
  "搜索邮箱...": "Tìm theo email...",
  "刷新当前列表额度": "Cập nhật hạn mức trong danh sách",
  "刷新 Codex 当前账号额度": "Cập nhật hạn mức tài khoản Codex hiện tại",
  "当前": "Đang dùng",
  "已复制": "Đã sao chép",
  "未获取数据": "Chưa có dữ liệu",
  "封号": "Bị khóa",
  "需重新登录": "Cần đăng nhập lại",
  "过期": "Hết hiệu lực",
  "刷新": "Cập nhật",
  "删除": "Xóa",
  "切换账号": "Chuyển tài khoản",
  "正在切换...": "Đang chuyển...",
  "账号到期日": "Ngày hết hạn gói",
  "到期日期": "Ngày hết hạn",
  "清除日期": "Xóa ngày",
  "取消": "Hủy",
  "保存": "Lưu",
  "保存中…": "Đang lưu…",
  "登录状态冲突警告": "Phiên đăng nhập chưa đồng bộ",
  "检测到官方 Codex 插件中存在未同步的 Token 更新。": "Codex có phiên đăng nhập mới chưa được lưu vào Switcher.",
  "以 IDE 状态为准": "Dùng phiên của IDE",
  "继续切换": "Vẫn chuyển tài khoản",
  "周期保鲜": "Giữ cửa sổ hạn mức hoạt động",
  "保鲜已关": "Đã tắt duy trì cửa sổ",
  "套餐待同步": "Chưa nhận diện gói",
  "未知": "Chưa xác định",
  "已停止": "Đã dừng",
  "仅本机": "Chỉ máy này",
  "局域网可用": "Có thể dùng trong mạng LAN",
  "设置": "Cài đặt",
  "统计": "Thống kê",
  "缓存": "Bộ nhớ đệm",
  "路由": "Định tuyến",
  "代理": "Proxy",
  "账号": "Tài khoản",
  "重试": "Thử lại",
  "加载用量...": "Đang tải hạn mức...",
  "确认": "Xác nhận",
  "关闭": "Đóng"
};

const ENTRIES = Object.entries(VI_TRANSLATIONS).sort((a, b) => b[0].length - a[0].length);
const ATTRS = ["title", "placeholder", "aria-label", "alt"];

function viText(input: string): string {
  const trimmed = input.trim();
  const exact = VI_EXACT[trimmed];
  if (exact) return input.replace(trimmed, exact);
  if (trimmed === "Skills") return input.replace("Skills", "Kỹ năng");
  if (trimmed === "Proxy OFF") return input.replace("Proxy OFF", "Proxy TẮT");
  if (trimmed === "Proxy ON") return input.replace("Proxy ON", "Proxy BẬT");
  let out = input;
  for (const [zh, vi] of ENTRIES) {
    if (out.includes(zh)) out = out.split(zh).join(vi);
  }
  out = out
    .split("，").join(", ")
    .split("；").join("; ")
    .split("：").join(": ");
  // Final UI guard: never leak untranslated Han characters into the Vietnamese
  // interface. Brand/protocol names are authored directly in Latin script
  // (GLM, Kimi, MiMo, Qwen, Responses, Chat Completions), so this only removes
  // stray particles left by legacy Chinese copy such as “吗”.
  out = out
    .replace(/[\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF]+/g, "")
    .replace(/[ \t]{2,}/g, " ");
  return out;
}

function translateElement(el: Element) {
  for (const attr of ATTRS) {
    const value = el.getAttribute(attr);
    if (!value) continue;
    const next = viText(value);
    if (next !== value) el.setAttribute(attr, next);
  }
  if (el instanceof HTMLInputElement && (el.type === "button" || el.type === "submit" || el.type === "reset")) {
    const next = viText(el.value);
    if (next !== el.value) el.value = next;
  }
}

function translateTree(root: Node) {
  if (root.nodeType === Node.TEXT_NODE) {
    const value = root.nodeValue ?? "";
    const next = viText(value);
    if (next !== value) root.nodeValue = next;
    return;
  }
  if (root instanceof Element) translateElement(root);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    if (node.nodeType === Node.TEXT_NODE) {
      const value = node.nodeValue ?? "";
      const next = viText(value);
      if (next !== value) node.nodeValue = next;
    } else if (node instanceof Element) {
      translateElement(node);
    }
  }
}

export function installVietnameseUi() {
  document.documentElement.lang = "vi";
  const apply = () => translateTree(document.body ?? document.documentElement);
  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) {
      if (m.type === "characterData") { translateTree(m.target); continue; }
      if (m.type === "attributes" && m.target instanceof Element) { translateElement(m.target); continue; }
      for (const node of m.addedNodes) translateTree(node);
    }
  });
  observer.observe(document.documentElement, {
    subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ATTRS,
  });
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", apply, { once: true });
  else queueMicrotask(apply);
}
